dist: xenial
sudo: false

language: python

git:
  depth: false

python:
  - 3.7

install:
  - git clone git@github.com:${TRAVIS_REPO_SLUG}.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - pipenv install

script:
- pipenv run build

deploy:
  provider: pages
  fqdn: renaissance.pub
  github-token: $GITHUB_TOKEN
  local-dir: build

  skip-cleanup: true

  target-branch: master
  on:
    branch: source
