dist: xenial
sudo: false

language: python

git:
  depth: false

python:
  - 3.7

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_BRANCH
  - pipenv install

script:
- pipenv run build

deploy:
  provider: pages
  fqdn: renaissance.pub
  github-token: $GITHUB_TOKEN
  local-dir: $TRAVIS_REPO_SLUG/build

  skip-cleanup: true

  target-branch: master
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(source|v[0-9\.]+)$
